#!/usr/bin/env bash
# Bash script that

# Deletes the file /var/run/myscript.pid
delete()
{
	rm -f /var/run/myscript.pid
	exit 0
}

# Write PID to file
echo $$ > /var/run/myscript.pid

# Display message indefinitely
while true;
do
    echo "To infinity and beyond"
    sleep 1
    # Trap signals and handle them appropriately
    trap 'echo "Y U no love me?!";' SIGINT
    trap 'echo "I hate the kill command" && delete' SIGTERM
    trap 'delete' SIGQUIT
done
