#!/usr/bin/env bash
# This script displays To infinity and beyond indefinitely
# Add a sleep 2 between each iteration of the loop and
# I am invincible!!! when receiving a SIGTERM signal

trap "echo I am invincible!!!; exit" SIGTERM

while true;
do
	echo "To infinity and beyond"
	sleep 2
done
