#!/usr/bin/env bash
# This bash script displays numbers from 1 to 100 'fizzbuzz'

for i in {1..100};
do
	if [ "$((i%3))" == 0 ] && [ "$((i%5))" == 0 ]
	then
		echo "FizzBuzz"
	elif [ "$((i%3))" -eq 0 ]
	then
		echo "Fizz"
	elif [ "$((i%5))" == 0 ]
	then
		echo "Buzz"
	else
		echo "$i"
	fi
done
