#!/usr/bin/env bash

s1="bad luck"
s2="good luck"
s3="Best School"
i=1

while [ $i -le 10 ];
do
	if [ $i -eq 4 ]
	then
		echo "$s1"
	elif [ $i -eq 8 ]
	then
		echo "$s2"
	else
		echo "$s3"
	fi
	((i++))
done
