#!/usr/bin/env bash

s1="bad luck from China"
s2="bad luck from Japan"
s3="bad luck from Italy"
i=1

while [ $i -le 20 ];
do
	case $i in
		4)
			echo "$i"
			echo "$s1"
			;;
		9)
			echo "$i"
			echo "$s2"
			;;
		17)
			echo "$i"
			echo "$s3"
			;;
		*)
			echo "$i"
		esac
	((i++))
done
