#!/usr/bin/env bash
# THis bash script displays the content of the current directory...
# in list format 
# Where only the part of the name after the first dash is displayed

LIST="$(ls)"
for i in $LIST;
do
	NEWNAME=$(echo "$i" | cut -d'-' -f2-)
	echo "$NEWNAME"
done
